# Generated by Django 3.2 on 2023-06-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230622_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForMessage',
            new_name='ContactFormMessage',
        ),
    ]
